# Generated by Django 4.2.24 on 2025-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_branch_unique_together_branch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('branch', 'number')},
        ),
    ]
