# Generated by Django 4.2.24 on 2026-01-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_tag_budget_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['number']},
        ),
    ]
