# Generated by Django 4.2.24 on 2026-02-17 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0011_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('patch', 'Правка в ветках бота'), ('mailing', 'Рассылка'), ('build', 'Сборка бота')], max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Непрочитанное'), ('in_progress', 'В процессе'), ('done', 'Готово')], default='unread', max_length=20)),
                ('cjm_url', models.URLField(blank=True, default='')),
                ('tz_url', models.URLField(blank=True, default='')),
                ('build_name', models.CharField(blank=True, default='', max_length=255)),
                ('build_token', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='task_requests', to='marks.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
