# Generated by Django 4.2.24 on 2026-02-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0012_taskrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
