# Generated by Django 4.2.24 on 2026-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0019_experiment_dashboard_url_experiment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bot',
            name='platform',
            field=models.CharField(choices=[('tg', 'Telegram'), ('vk', 'VK')], default='tg', max_length=10),
        ),
    ]
