# Generated by Django 4.2.24 on 2026-04-08 18:16

from django.db import migrations, models
import marks.models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0023_experiment_comparison_text_experiment_technical_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequest',
            name='photo',
            field=models.FileField(blank=True, default='', upload_to=marks.models.task_request_photo_upload_to),
        ),
    ]
