# Generated by Django 4.2.24 on 2026-05-25 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marks", "0025_taskrequest_feedback_columns_portable_after_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("hypothesis", models.TextField(blank=True, default="")),
                (
                    "test_dimension",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "Текст сообщения"),
                            ("offer", "Оффер"),
                            ("send_time", "Время отправки"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "traffic_split",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("50_50", "50/50"),
                            ("70_30", "70/30"),
                            ("other", "Другое"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "traffic_split_other",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Подготовка"),
                            ("draft", "Разработка"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершен"),
                            ("success", "Успех"),
                            ("failed", "Провал"),
                            ("retest", "Нужен ретест"),
                        ],
                        default="backlog",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing_experiments",
                        to="marks.bot",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing_experiments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailingVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("weight", models.PositiveIntegerField()),
                ("message_text", models.TextField(blank=True, default="")),
                ("offer_text", models.TextField(blank=True, null=True)),
                ("send_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="marks.mailingexperiment",
                    ),
                ),
            ],
            options={
                "ordering": ["experiment_id", "label", "id"],
            },
        ),
        migrations.CreateModel(
            name="MailingVariantMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent", models.PositiveIntegerField(default=0)),
                ("delivered", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric",
                        to="marks.mailingvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipients",
                        to="marks.mailingvariant",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="marks.mailingexperiment",
                    ),
                ),
            ],
            options={
                "ordering": ["experiment_id", "external_id"],
            },
        ),
        migrations.AddField(
            model_name="mailingexperiment",
            name="winner_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winner_of",
                to="marks.mailingvariant",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailingvariant",
            constraint=models.UniqueConstraint(
                fields=("experiment", "label"),
                name="uniq_mailingvariant_experiment_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailingrecipient",
            constraint=models.UniqueConstraint(
                fields=("experiment", "external_id"),
                name="uniq_mailingrecipient_experiment_external_id",
            ),
        ),
    ]
