# Generated by Django 4.2.24 on 2026-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marks", "0026_mailingexperiment_mailingvariant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingvariant",
            name="start_param",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
