# Generated by Django 4.2.24 on 2026-08-03 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0027_shortlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtmDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('source', 'source'), ('medium', 'medium'), ('type', 'тип'), ('direction', 'направление'), ('funnel', 'воронка')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('group', models.CharField(blank=True, default='', max_length=255)),
                ('is_template', models.BooleanField(default=False, help_text='Шаблон-маска (напр. tg-<имя>), а не прямой выбор')),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['field', 'value'],
                'unique_together': {('field', 'value')},
            },
        ),
        migrations.CreateModel(
            name='MarkedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=2000)),
                ('utm_source', models.CharField(max_length=255)),
                ('utm_medium', models.CharField(max_length=255)),
                ('utm_campaign', models.CharField(max_length=255)),
                ('utm_term', models.CharField(blank=True, default='', max_length=255)),
                ('utm_content', models.CharField(blank=True, default='', max_length=255)),
                ('mark_type', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('funnel', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('full_url', models.CharField(max_length=2500)),
                ('pending_review', models.BooleanField(default=False, help_text='Шаблонный source — на заявку Грише')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_links', to=settings.AUTH_USER_MODEL)),
                ('short_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_links', to='marks.shortlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
