# Generated by Django 4.2.24 on 2026-05-31 13:06
# Manually edited to preserve MailingExperiment.bot -> bots data via RunPython.

from django.db import migrations, models


def copy_bot_to_bots(apps, schema_editor):
    """Copy single FK bot_id into the new M2M bots table before bot is removed."""
    MailingExperiment = apps.get_model("marks", "MailingExperiment")
    Through = MailingExperiment.bots.through
    rows = MailingExperiment.objects.exclude(bot__isnull=True).values_list("pk", "bot_id")
    to_create = [
        Through(mailingexperiment_id=experiment_pk, bot_id=bot_id)
        for experiment_pk, bot_id in rows
    ]
    if to_create:
        Through.objects.bulk_create(to_create, ignore_conflicts=True)


def noop(apps, schema_editor):
    """Reverse migration cannot meaningfully restore the FK; leave M2M intact."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("marks", "0027_mailingvariant_start_param"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingexperiment",
            name="bots",
            field=models.ManyToManyField(
                blank=True, related_name="mailing_experiments", to="marks.bot"
            ),
        ),
        migrations.RunPython(copy_bot_to_bots, reverse_code=noop),
        migrations.RemoveField(
            model_name="mailingexperiment",
            name="bot",
        ),
        migrations.AddField(
            model_name="mailingexperiment",
            name="tz_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
