# Generated by Django 4.2.24 on 2026-08-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0028_utmdictionaryentry_markedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pending_review',
            field=models.BooleanField(default=False, help_text='Шаблонный source — на заявку Грише'),
        ),
    ]
