# Generated by Django 4.2.24 on 2026-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0030_tag_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('delivered', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
